### ISSUE TITLE
SMIL format, using relative path or absoult links ?

### ISSUE THREAD

**Issue by joelBrun** [awsdocs/aws-elemental-mediapackage-user-guide#2]
Hi, I'm following the doc for using smil with mediapackage : 
[doc_source/supported-inputs-vod-smil.md](https://github.com/awsdocs/aws-elemental-mediapackage-user-guide/blob/master/doc_source/supported-inputs-vod-smil.md)

but it's not explicite if the file should be relative to the s3 bucket, to the smil path on the s3 bucket or need to be absolute HTTP url...

**Comment by jrochkind** [comment]
same question!

**Comment by eaputnam** [comment]
Sorry for the delay. After speaking with the team, it's relative to the manifest location.
